Update script

diff --git a/script b/script
--- a/script
+++ b/script
@@ -28,7 +28,10 @@ hwclock --systohc
 read -rp "Specify one basic locale to generate (for help, see locales-help file in the repo): localegen
 echo ""$localegen"" > /etc/locale.conf
 sed -i '/"$localegen"/s/^#//g' /etc/locale.gen
-locale-gen
+while ! locale-gen; do
+echo "Couldn't find such a locales. Tip: remember to use a correct format, for help see locales-help file in this repo)"
+read -rp "Specify one basic locale to generate (for help, see locales-help file in the repo): localegen
+done
 read -rp "Specify hostname: " hostname
 read -rp "Specify username: " username
 while ! useradd -m "$username"; do
