Update script

diff --git a/script b/script
--- a/script
+++ b/script
@@ -27,7 +27,10 @@ do
     case $opt in
         "UEFI")
     pacman -S grub efibootmgr --noconfirm
-    read -p "Podaj sciezke partycji EFI (oczekiwany format: /dev/sda1): " efidir
+    while [[ $efidir != /dev/sd[a-z][1-9] ]]; do
+    read -p "Podaj sciezkie partycji EFI (e.g. /dev/sda1): " efidir
+    [[ $grubdir == /dev/sd[a-z][1-9] ]] || echo "Niepoprawny format"
+    done
     mount --mkdir "$efidir" /boot/efi
     genfstab -U
     grub-install --target=x864_64-efi --efi-directory=/boot/efi --bootloader-id=archlinux
@@ -36,7 +39,10 @@ do
     ;;
         "BIOS")
     pacman -S grub --noconfirm
-    read -p "Podaj sciezke dysku, na ktorym powinien zostac zainstalowany GRUB (oczekiwany format: /dev/sda): " grubdir
+    while [[ $grubdir != /dev/sd[a-z] ]]; do
+    read -p "Specify the path of the disk on which grub is to be installed (e.g. /dev/sda): " grubdir
+    [[ $grubdir == /dev/sd[a-z] ] || echo "Invalid format"
+    done
     grub-install --target=i386-pc "$grubdir"
     grub-mkconfig -o /boot/grub/grub.cfg
     break
